# workflow -> Pipeline
# workflow name
name: CD Pipeline

# event on which you want this pipeline to be triggered
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

# jobs
jobs:
  build:

    # server
    runs-on: ubuntu-latest

    # versions you want to test your app on
    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
        # switch branch
    - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    #     # actual commands
    - name : Build Docker Image
      run: docker build -t yugcoder/youtube_backend:latest .

    - name: Docker Login
      run: echo "${{ secrets.YB_DOCKERHUB_PASS }}" | docker login -u "${{ secrets.YB_DOCKERHUB_USERNAME }}" --password-stdin

    - name: Login Successful
      run: echo "Docker login successful"

    - name: Push Docker Image
      run: docker push yugcoder/youtube_backend:latest

 